dae_nodes:
    - ENC[AES256_GCM,data:WlsovypK56yJ2hCgwVmRCWk/4k4FLLXw8KlR3mjhPzdVG/BVyTVXYEeyvPu2FSNkTChkK3YsHxmlwtmhlEgeFSvPCpWudA2Gk6Y6pBQf0HapeQxiNCm+MSzikC8VsKmBTIwvRK4low1PHfc9sBGc03MOThcDXiuJB1hFw/M1kZ/D4Sc5teQwqcYqRWtNiw==,iv:9unQPXZEGEmJxCB7iE3a6GpFkyjzSt1OQKccZIhH7c8=,tag:c/CEtpkBZbm2+ycWzP7EeQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlykqmG6KEj9d7gAoCxOGkdEMjaxvHU1FSEyi/xVYz1 2985258+centsent@users.noreply.github.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGVqV3A0USBYaHBR
            YkdRYmJxV2J5aHN3cHVORFRyTmpmNzh0MXJLTTRYUWdDK3lPMGlvCkdkbTVjZS90
            eUV5SStWSVFxbXc4bm5jWll6UzlHZFdxUW9wZUYybndSck0KLS0tIEFESG1GeHJS
            VFFZMm9YNCtxQ2F2TU9ocURkbUZ5Y2VGVWQzTHdaeFJ6ZkkKJHQYFvzocHsfAsdO
            a7sq8CDi8AQg6EAF6oF5AEtnAip4vNwqQ9KIXFCELjK4ns7OngkHaYb8g1Nbxuwy
            MOrCgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDtwyO8a6Ki9TMJPwROQAPXZuvtnidiJgSfFoi1mGKt/ theodo@venomous.local
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1SUU84ZyBYVkZG
            TnhtNFJWNHM1d3pQNEdSbU9pMlZ0aGorYTRTK09SMml2ZkhpVEhRCi91SkVuMXg2
            eUxFWUZ6cEpsTGpWTTEzRFRPM0w5QUZOWlNzclJxODU5QkkKLS0tIGhuMlBza25s
            NktWN2JFMVJDSlhkTkphazE2VWtma2tMaFZTdHRMQVJJLzgKFngue/gRVpB1B/li
            KRNCVge92futLxXRc0DCs6YrS8l0bA5kTZo190bAEqNYKAZOHBfrVCW2q6bojxok
            /ganfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOXQ07lpU69v4CK9Kvt1Pw84wkd7VGHNSZc7ZlDosOhWkdJJOmO6ydrdoHHRexbV9nVe6bRQ2vdIymS265J8o6W2N+FDnBfRZMzsaS4H3+QDLoPS3998OJ2igM8xgomclFdKC+G22coqQwcnxZX/r3znQ0cFeYdtJRs1/4oySk0sX5pUOoRF62Bx8NDi+lAZMOxlAsBxJ7iLD8k1u9Oy+IMkD218Jset8zQzDI54ddEcqTLrETkHQ+XJbzlwbWYIbf3JmzSkDnEAep1WIJIAdxk4QfKm2YBJBk6z9r2Yp6FxKRW2/qp/9vSAi0c4xaytifpuDjo+fj3qoD2HGXNnqxWtKDDJM7w6/PfNK0+avqNMi0Aclo9keN/UdSjF+ZlcPuMr8TrOC4snSV5qe63xThteLG9bVC+xLosz2+FMt7Sgr0OylrWXNdRL7l9uNh0E/c4K9JreWlBPinEUmd6KJ+2dGs7j4ARPT21Hkp54BYEHsEIJNJcD2M4dESWuO+z1sG2ClXz/s/xlrkxXU/VJoLqRY+wDtx/rrzd38rVF2levL34BkA37DuOrtUu+Mfh6gvlHFDbpkEo28QzdLP9km7cValztZEqm3jgff/KTIK7sYjmkXTX+PsFNcTHQ3DSR7pb6GDXcvuuGwrrJ9bm9mG/5bAI0vGMLFXlLuYF3sQKQ==
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgQ1ZKL3RnCkNTOFlSakJJ
            SlZGU0lSOXFCUTdlUjE0aldXMlFESWI1QmcxSjNqMTk4UDBrY2U3SFVSUnU4SERU
            V2piVmhDMi8KZm5ibjhsekdKa0RUdDlhejBWc2VHRmVwSy9lWEdNSjhoRjB1ZnNr
            R1NpS3hteVB4dkM1cGIvRHBqWGZTd203awp5V0x1NDVHMTB4NGcwWW1tVmxXcFNE
            NzV3NlpyUExPbHlYV05HakZ3ZHFKR0dQekhqOTc3K0ptdE02WHlWc1lwCnR2cEdo
            em0wQWRrOHltK2l6OUpIeUR4SmMrTGtqbGN5ODhGZXArOXZzWlpnUGp3MEtneGZ1
            Ui9CclNFN1BlMlQKc3FybHp2L280ajdXS2dUMkJyL3Q1R2pXS2g1WkpGTVlIWmhG
            NlJPMGxjV3A2K09OV0xIY0MrS1ZjTU01WjBjegpza3hNNmVpY3FOaXZHOGVvZHlX
            Z3dJK214QmYxbFVreHB5b2Y4a3VGNDA2V29JZFJXU0QxUU5pVy9jQkQyUjZhCkpW
            NUZYdVpiS1hBUEtOcGpTTzNqcVQ2aG9leVZJMW9WSnFNN3NlRnEzUmVhMzZIKzgv
            aVZOKzZKYnBUNXBER3gKaVEveGNoTmwvbGgzSUhmZk52dmpqdGFCdis0YytYQnVZ
            cDlDaXpqa1FwTWQzeDk5cFYwQVJvN29wQXNBWW16YwpZaDFoeDRsajBBL1IzVzRH
            SE0ycHVOZXpmOFNDVmpGeWhDTUpqdVFHNlkwSUdMNU5VaU9UWFp2c2tZTFIxM3E5
            CnZGV0czU3M1N2VBWjhZOFJVL1JudTllL3o0Y0xPYWx3VFRwKzRxLzlZQ0xhQ2hN
            QVhPWnNPVTlaekcvT3F6eW0KRHhJTFJaWmhudEJkZjIyNmdPZ1NpMzExUU5JVTkr
            SUgvOFpHRmlOckRIUQotLS0gS2prR3hHY0ppUWdpNEFTZFdXcndBNEtyY0RvNWdD
            RERLaXpZTC9pQkNNWQoC1f5sgfG9fmyMV6DJ6eBEAl/H8T4XcrLFRlPmFkJ9SY/e
            ASwUjSeDJ22bigey2JPb2+Bofpm617s2AQzfucdq
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMHM3FMPY9uo3r5dr+YfKEgQb0lPW7z6Jz1s9oH1cZry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE5zY2FuUSA3NVor
            akRBazYxMmU5NEtaRUNKWmt6QWRuL3diWERjd3JESnI2dUVhYUZ3CjRhd011bVVv
            d1JFSVRaSno3THVreG1VL1RFc2hWcXZienVRNDBja2Y2ZVkKLS0tIDE0MVJqWEdY
            RHBlUU9RNTZ0UjdwWXdBVVpac2FvL1duNjE5S2liWXlYamMKq7gn5vzHcobo4+65
            0k59r6fbc85k1fdwacR/S0E+MhZGPq/54pKcsmRcpA1NIj3h3BISBZnG0chP18bG
            i/A3Dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbT9HNzbFVHV3lbm0LadQGfkg5vdPDaCF5HF/8aTMbPfHB/b/NpXwAmsempvUxjCvCVHjP0XZ8vdocNmUSYrxzn3zfV62mCWKtEUhNNrEyqIGcAMWilEdAQMNsUFWbjcUW4A+RturuYmNe1d5Mpk/WK8KVSib/tfvytJnkBIh84AJSgZvLjh5KNH3NIHPpa3hPwwlW6x8zMJzXn4a0N/0L5dBE+Evn3mrzXaCi2Y5TPZEhbFRB8rP/oCZSraJB1Elymytlym1Za8QY0mXV3lw8TyrOQKQlbJCFWsqDeLWilFoXnGLbuEbexhQr0JW+ZQHM23EI8mylZYvV8zMcFRLHsU8Nyprl0+h34ePFuVjD0KtSraSfJDOdstvwxo3Cx+99CeMiswJfBGrpWoFQJ4wmdZX12gOtdsyenq1mySmhC0O+rjp3stkmvv0hv0PnGsz7gysMcA2qRY6vJo2MH+oSTtXwLomloUS80fan9+7w+ecCr0Wz/X05IDT2rzfObUk=
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgbjRobHdBCkQ2eE9nN01F
            V0FRTGxtcTU2V0t0YzI5RDlld3FyZnJFdnpEQ3M1RHR1UlFCZ3ROU3RkODJ5Zmt5
            OWtCMExITDAKT2xMeGpTMTNCOHFzRUJxRW1iRXZ6cmFxb0phVXRKV1JRNjZldTdU
            K1QrZ2RYWGRvNElJVEZDRzN3U2ptK2ltQwpic0ZzYk52dDhTd0ZhWDhJd0FrcVAw
            MTJUc21VUTl4a3ZieHB3VWhDeHV3N3NXeE4yd2Q3OUNoblhzV2NoZEtSClBYcnEr
            QUd2TVFKcnJXWHNMdG1OMi8wZkQyc0I2TVprVUFzaHgzb2V4S1VxSkZHcVozdUZr
            SXhuRFdqVTZpWU4KYXhqOGp4WEdYc29Mby9UanhWNTU0M3hGdmR0TW9LMjBpVzVH
            WDhwZ2lpTk9WajVGRlZFL2w3YnRWUnNydGhFSwovcFNwdjNsSUwvSFhEeFk5T2dk
            a3NZN1U5QVlUVU9tSGpxL0tzb3lGTVNlRG5IYUpwcDN4bFF4cHFLOFVHL1hJCjds
            Smp1eFZTem0xVHNDU21UbE9OUzQ3NU92UWpQbllSRVdZWFFUemkvbmJQa2V6ZzF5
            czF5aFkwaDZzMVpGMUoKcnY0Nk1uSFJXYU0vZXBYcGExTGRuNFFxM1VXY1lNQnBZ
            Nis0a2VoSHdEQlE4TnZDU2ZIWW9HWGlOODBBQkdzbAoKLS0tIGNKOUdOaVJ0UzIz
            Tjh5dEdDWkZyOUNwdWxOZ1VhSzMxdERaR3N6T1ZwZEUKdwOKjutvDP2NhRkZHkze
            mJ+gWblIdRAZ+n74zCi6/LZfsI29rSy/70dByWEiJhOuMQZwr9KAaUKHkt41qjTt
            sA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvGtpOtmxIN9svylA6BM8PEpSyJv8BIvfD7bE62dYKN
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlibWpBdyA2QURX
            eHlsdGJMOU9lc25LSTliQ3NzbFVmL1UwekViZmdkeldDd2FsVzEwCmlsOGxPMFVq
            NFI5dHd2dHJ4NUk2SU96dFg4OElvS2MwQlVHbDNDTWpxZEkKLS0tIEhxMER4TDhV
            dmh1VmFjR29GeUNVWWJCNXJqQWdjcm45RUJsT2RBOEIzL1EKxyjI9ahDCvfQx4Tt
            sYSnh1pCxkN/G0qGmR3yr0ZnI1uHF3q5RNa9NUTOHEbT1tgHy6KwJKuDnaVBKpTg
            kdGSmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCanBIFIA+kfP972bw9Csa7ENC5Vb3zHjddxgn4DryRFdPHJIdAxkzOSPkJMF9f8HnMnzg8nIwD6ZzPCu6JkN15DEkSKySX4X4wf6bNYAoWUx45NkdB0S8RnNeAkwRLovZgWw/sJTsLYbqOorpkQv9aeus0YxmBP8AenVuQinx+qqMwXbQyyI8ps+qC2550ZYn3EOLcN1gZJvheJmOVGkNa/gcGB3cgb1AEA9W4ClLxpJuYyfhAQsPi1lOL09/D5sLahtJqP4Ymkc9iSqQGg6YBNeQ2YU1p+VOnHbMgx4nR6MA9zvD8EZZKEfcmvBLGPoBjJHXwA0ZByFdk+le8Os43JeVc8YxPhewno9GZK8GTjJkKrRM31UT0HOy64AT6h9plt0e1vASnJYIXU2pW1gyszGvsyNVBMiIHncUpDNZpijMhbn0hsfbM+ad8vjduFZbUY8hBNTHRR/QmxXVbtSw9RqCQmef55WJoV/ke4/mmcDzEfOi41pnD8yPErGwxuqOryge1uNJ16aFo/o+ZGFPuU4i+JqgqzJKHIYbatv2Y8KtLRjYnWyU0HvCQ7XEaf9sfWyL/vDKmXOMCuoxSXjQU79qtTYuUDDN4tNMRKZKtyaQiptiDRtwY0ZPiWt1v8VXXwC3pqW7WKSZmrI+5BFsg64BlBNWiNtc3FSJORg4E4Q==
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgVzJjSWNRCmJWUVBvSXdJ
            eWpkeThhT0lMbGZxVkJNQXN0Nk1DNnZWRlJZYlc3bzZEN1M1OGh0ei9YUVlmM0pC
            YTQ4QmZBYXIKbVJFVlZxUEMxYU1RNjhqTVQxMEk0UFAzYUZldnhVaEZpWjJHMUg3
            SGM4MkxBeGNHK2haSjR5VEZ0Sms0ZVhHcgpXRGU5WW45NnE1TURURGpLSTJvR0JU
            UnpJakRXajZGSFJSbUswU1BFbEJqSGV0RmVLYUhKVHpkZ0hJNmEyNm1IClJlSlR6
            NnpmL3VwZWk4RThNQTUyeEk5ZWlKSlVxaHU2Ni8zL2NpOW1GOU9nRks4b0lxSmYr
            UHA0cWw0eVFaZjYKaW9lSEhoOXExSG96cTMxYUpHRU5zOXFBU3Y5SlRNYzd1WlZ1
            YmF2M3FlRUJ5YllVejdLWWxOMzJaNVI4a2lmdwpCbkZ6VE14bEpSOXNqMTJkYytq
            ZHE3Q0t5dHhXTEtRK0Q5V0MwWlJ1ZEl1RmNpOE9wVHJoRjRHaERVYTd3NVBlCnZJ
            dTFIMUo2dmVMYXl2N2wwRkhPNXJoTXVhY00vd0I4bGplOXFxK0dQendpdGFjVFB6
            NGxkak5QT0dVczhLWDkKMUJ5M1g3d3lUT0hodFBlY3ZMNlZUZjRBSkdJb0YyWXZx
            Nk1zNG15M3JqR1RZTDN0SlFrR2RHejRoVm0zSVVMZgpQWXBqNEF0eDFsMkU5WUlE
            eXBFNUhFeXlsVE1ib0xTMG95NlhnZjNjYzczMkNLNzlOb1hVWUlrc0c5eVR2aDJh
            ClQzL0c1d2JEVnUvU2VqOFowTGdTWW0xTCsxL2svUzFjajZjak9wQWpCdk16QXgr
            RlI4NUZpSkRnSWpmMDZFYW0KOVJzZmZ3WitBY1lzaTFzY2VYY1VpeVJZcDVORXNV
            U3lTOFAxN2plN1pSUQotLS0gZko4RzA3Q1NSTDhIQkRyd0cvTW1VdW04Y2FFZjJI
            YzZUeXhMejVkR0hkQQqlb+uypihdHZqGbcGbsoCLyCtZvvc9aqRzmecKzltkXxuo
            1oXLuDcIphaCGKAjL8aPmlFp7iYsicZA/HyMpKoU
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDhT7K9PjkVJzPQT3+UQ228iDS8Sibefrlskh6/TjW9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFl3NDNrQSBmQkhN
            R210TWJ6bWwwRllqQlpoK0RsUEgzTDFtNlNzV0pqQTBSUUpKRW5vCmtyMVBYVlpu
            N1RYQkxJcEE4R2x5dUJtaFF1LzQ0Vm1ocVcxcDkxME1EVHcKLS0tIDhPZG85U2dL
            UUZuUEVxb3ViTnlyZHFWZWI2akFBOHU2OFlYL2ZKeERXY0EKbx8jHqTEasjJLh2H
            FT3QbdEgwt9yuBKkxP1XG9MkjYY+qgxLs0uTnMIlT9US4O3xz68jHSM7sPQKp7Nn
            u+mccA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBW3bHKxBQUMxYrIJviPvrVZ97ahNKE0+34NxBCxZO6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFiWklvZyBKc1RF
            WjR6b3NjY0VHeUNjR2NXSGN3QlhhWGIvZmxEQ0ZYVmhicnFjT2dVCk5USkdMeHdz
            VE1pVVdGT0VtbUx4ODQ5YmNaMWdiLytycnYrditTbm5uN2cKLS0tIExBTHZuYTRu
            QzZ3dXdaeFM0R2RKbnlBc2xrbmFOK2QvQ3R5YkVYcU13QzQKPR8tvikUdt3AnmPO
            OME9ZFBG10kAKJY0ta8Su1TssXWGRq3o/u8K6iwJoPW8IBEVqQopnHIkdqELAL4B
            SvLQiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbyK/x32wFHfHT5V/pO+WriUAoF//lCd1ZKMvu2ByIF
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEZhWk5oQSBnSHRV
            VzNBNnRJTWdkZGRESm1WcXcyRzhTcDYrRm51T0p5cHZOek1sVGw4Ck50Nk1sUlB6
            NlFuU0dhN1QrV1RzbnpVeWd0SlZ4UTNFMFFMWENyYUx4MEUKLS0tIHc3cEFoNkVv
            UDhiR0p3cU9JN1REKzBkU1E4RGRrMjRNdVRoRUkzbEp0VmcK1PDn5AJZ/Jfv317x
            TF9SP8meGPErKxCz6jtHOAMfuYLMbeycRkirzHe5jceYoS2Rg+qAKevsAExWC4Hs
            B5MJog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T05:12:18Z"
    mac: ENC[AES256_GCM,data:DXJCGjeTwPwZ8nqlXb6zu2T/uYyIbSqbKHmR68gEa3Jip+fQgIAAsnCtuz92uxjYX12vUTYckqRGYbs1dlJ2JOsOGhTrWe8fAS81HWWh1WxA03vT0VyPG/3q01xSHGT/aguX7PPWwDfSahKuRC/7BUcS1vBl7QVaWJ+34YVMFxw=,iv:3ID7zzDIbNWhM1deAQOw3nIUxxwSh3dgVwbONszTfmU=,tag:y1H2U8v8QsAdKSoUHpT4Vg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
