---
dependencies:
  - role: grub
    tags: grub
  - role: portage
    tags: portage
  - role: dae
    tags: dae
  - role: greetd
    tags: greetd
  - role: nix_installer
    tags: nix_installer
  - role: common
    tags: common
