---
portage_packages:
  - app-arch/7zip
  - app-crypt/swtpm
  - app-containers/podman
  - app-containers/podman-compose
  - app-editors/vscode
  - app-emulation/qemu
  - app-emulation/libvirt
  - app-emulation/spice
  - app-emulation/virt-manager
  - app-emulation/virt-viewer
  - app-misc/mkcert
  - app-misc/tmux
  - app-office/libreoffice
  - app-portage/gentoolkit
  - app-shells/zsh
  - dev-build/cmake
  - dev-qt/qtwayland
  - dev-vcs/git
  - dev-util/android-studio
  - dev-util/android-sdk-cmdline-tools
  - gui-apps/tuigreet
  - gui-libs/greetd
  - media-fonts/font-isas-misc
  - media-fonts/arphicfonts
  - media-fonts/opendesktop-fonts
  - media-fonts/powerline-symbols
  - media-fonts/source-han-sans
  - media-fonts/wqy-zenhei
  - media-fonts/zh-kcfonts
  - media-libs/nvidia-vaapi-driver
  - media-sound/pavucontrol
  - media-sound/playerctl
  - media-video/ffmpeg
  - media-video/obs-studio
  - net-im/telegram-desktop
  - net-misc/chrony
  - net-misc/spice-gtk
  - net-proxy/dae
  - net-vpn/tailscale
  - net-wireless/blueman
  - net-wireless/wpa_supplicant
  - sys-fs/fuse
  - virtual/opengl
  - www-client/firefox
  - x11-apps/mesa-progs
  - x11-drivers/nvidia-drivers
  - x11-terms/alacritty
  - x11-terms/ghostty
  - x11-terms/kitty
  - x11-themes/papirus-icon-theme
